// GENERATED FILE — 请勿手改。
// 由 scripts/tools/gen_settings_search_index.dart 从设置页源码生成。
// 重新生成：dart run scripts/tools/gen_settings_search_index.dart

/// 设置搜索索引：label 取自各分类页 tile 的标题，category 为所属分类，
/// aliases 来自源码中的 `// search: ...` 标注（补充同义词匹配）。
const List<({String label, String category, String aliases})>
    kSettingsSearchIndex = [
  (label: 'OLED 纯黑深色', category: '外观', aliases: 'oled 纯黑 深色 黑色'),
  (label: '使用系统主题色', category: '外观', aliases: '系统主题 壁纸 莫奈'),
  (label: '封面动态取色', category: '外观', aliases: '动态取色 封面'),
  (label: '主题色', category: '外观', aliases: '主题 颜色 换肤'),
  (label: 'app全局字体', category: '外观', aliases: '字体'),
  (label: '启用自定义背景图片', category: '外观', aliases: '背景 图片 壁纸'),
  (label: '选择背景图片', category: '外观', aliases: '背景 图片 选择 更换'),
  (label: '清除背景图片', category: '外观', aliases: '背景 图片 清除 移除'),
  (label: '背景图片模糊', category: '外观', aliases: '模糊 高斯模糊 背景'),
  (label: '背景图片透明度', category: '外观', aliases: '透明度 背景'),
  (label: '按背景图莫奈取色', category: '外观', aliases: '莫奈 取色 动态取色 背景'),
  (label: '文字阴影', category: '外观', aliases: '阴影 文字 可读性 背景 壁纸'),
  (label: '歌词双击跳转', category: '播放页样式', aliases: '双击 跳转'),
  (label: '歌手写真背景轮播', category: '播放页样式', aliases: '写真 背景 轮播'),
  (label: '轮播间隔', category: '播放页样式', aliases: '写真 轮播 间隔'),
  (label: '写真背景透明度', category: '播放页样式', aliases: '写真 透明度'),
  (label: '男女对唱歌词优化', category: '播放页样式', aliases: '对唱 男女'),
  (label: '歌词动态颜色', category: '播放页样式', aliases: '动态颜色 混色'),
  (label: '歌词高斯模糊', category: '播放页样式', aliases: '高斯模糊 模糊'),
  (label: '歌词辉光效果', category: '播放页样式', aliases: '辉光 发光'),
  (label: '辉光触发阈值', category: '播放页样式', aliases: '辉光 发光 阈值 灵敏度'),
  (label: '背景动态流光', category: '播放页样式', aliases: '流光 背景'),
  (label: '歌词省电模式', category: '播放页样式', aliases: '省电 限帧'),
  (label: '音乐频谱环绕', category: '播放页样式', aliases: '频谱 环绕 可视化'),
  (label: '频谱柱数量', category: '播放页样式', aliases: '频谱'),
  (label: '频谱动态取色', category: '播放页样式', aliases: '频谱 取色'),
  (label: '频谱柱状图透明度', category: '播放页样式', aliases: '频谱 透明度'),
  (label: '频谱曲线透明度', category: '播放页样式', aliases: '频谱 透明度'),
  (label: '频谱背景透明度', category: '播放页样式', aliases: '频谱 透明度'),
  (label: '频谱背景高度', category: '播放页样式', aliases: '频谱 高度'),
  (label: '翻译歌词', category: '歌词', aliases: '翻译'),
  (label: '罗马音歌词', category: '歌词', aliases: '罗马音 拼音'),
  (label: '优先翻译（同时存在时）', category: '歌词', aliases: '优先 翻译'),
  (label: '解锁桌面歌词', category: '歌词', aliases: '桌面歌词 桌面'),
  (label: '蓝牙歌词', category: '歌词', aliases: '蓝牙'),
  (label: '压缩封面图', category: '歌词', aliases: '蓝牙 封面 压缩'),
  (label: '锁屏歌词（实验性）', category: '歌词', aliases: '锁屏'),
  (label: '锁屏歌词字号', category: '歌词', aliases: '字号 大小'),
  (label: '锁屏歌词粗细', category: '歌词', aliases: '粗细 加粗'),
  (label: '网络音质', category: '播放', aliases: '音质 清晰度 wifi 移动'),
  (label: '自动领取VIP', category: '播放', aliases: 'vip 会员 自动领取'),
  (label: '32bit 播放支持', category: '播放', aliases: '32bit 无损 高解析 音质 float'),
  (label: '均衡器', category: '播放', aliases: 'eq 均衡'),
  (label: '暂停淡入淡出', category: '播放', aliases: '淡入淡出 渐变 音量'),
  (label: '允许与其他应用同时播放音频', category: '播放', aliases: '音频焦点 忽略焦点 同时播放 共存 不被打断 焦点'),
  (label: '播放时保持屏幕常亮', category: '播放', aliases: '屏幕常亮 常亮 息屏'),
  (label: '播放 MV 时自动画中画', category: '播放', aliases: '画中画 pip 悬浮'),
  (label: 'MiniPlayer 滑动切歌', category: '播放', aliases: 'miniplayer 迷你播放条 滑动切歌 切歌'),
  (label: '收藏歌单按最近点击排序', category: '播放', aliases: '收藏 歌单 排序 最近点击 顺序'),
  (label: 'USB 独占输出', category: 'USB 独占', aliases: 'usb dac 独占 音频'),
  (label: '播放 MV 时自动关闭独占', category: 'USB 独占', aliases: 'usb 独占 mv'),
  (label: '主页 Tab 管理', category: '主页管理', aliases: 'tab 标签页 主页'),
  (label: '桌面快捷方式', category: '桌面快捷方式', aliases: '快捷方式 快捷 长按'),
  (label: '本地数据接口', category: '在线音乐', aliases: '接口 本地服务器 api 在线音乐'),
  (label: '清除缓存', category: '缓存与数据', aliases: '缓存 清除'),
  (label: '数据迁移（修复数据混乱）', category: '缓存与数据', aliases: '迁移 数据 修复'),
  (label: '应用版本', category: '关于', aliases: '版本 检查更新'),
  (label: '更新最新版本', category: '关于', aliases: '更新'),
  (label: '新手教程', category: '关于', aliases: '教程 引导'),
  (label: '用户协议', category: '关于', aliases: '协议 条款'),
  (label: '免责声明', category: '关于', aliases: '免责'),
  (label: '开源许可', category: '关于', aliases: '开源 license 许可'),
];
